//! Integration and specification test suite for Phase 8.4 — DNS Configuration Observation.

use netra_core::id::DeviceId;
use netra_core::network::ip::IpClassification;
use netra_core::observation::{
    ConfidenceScore, DnsObservationPayload, DnsServerRecord, Observation, ObservationPayload,
    ObservationType, PostureScanner, PrivilegeStatus, SensitivityLevel, TargetDescriptor,
};
use netra_core::storage::repositories::queue::ObservationQueueRepository;
use netra_core::storage::{DatabaseEngine, ObservationStatus};
use netra_platform::scanners::linux::dns::parse_resolv_conf;
use netra_platform::scanners::PlatformDnsScanner;
use std::net::IpAddr;
use std::str::FromStr;
use std::sync::Arc;

#[tokio::test]
async fn test_native_platform_dns_scanner_execution() {
    let device_id = DeviceId::new();
    let scanner = PlatformDnsScanner::new();

    assert_eq!(scanner.scanner_id(), "scanner.dns.v1");
    assert_eq!(scanner.domain(), ObservationType::Dns);

    let obs = scanner
        .scan(&device_id)
        .await
        .expect("Native DNS scan must not panic");

    assert_eq!(obs.schema_version, 1);
    assert_eq!(obs.device_id, device_id);
    assert_eq!(obs.scanner_id, "scanner.dns.v1");
    assert_eq!(obs.observation_type, ObservationType::Dns);
    assert_eq!(obs.sensitivity, SensitivityLevel::Internal);
    assert_eq!(obs.evidence_hash.len(), 64);
    assert!(
        obs.duration_ms < 5000,
        "Scan must complete within 5 seconds"
    );

    #[cfg(windows)]
    {
        assert_eq!(obs.privilege_level, PrivilegeStatus::Available);
        assert_eq!(obs.confidence, ConfidenceScore::KERNEL_AUTHORITATIVE);

        if let ObservationPayload::Dns(payload) = &obs.payload {
            for server in &payload.dns_servers {
                assert!(!server.server_address.is_empty());
                let parsed = IpAddr::from_str(&server.server_address).expect("Valid IP address");
                assert_eq!(server.is_ipv6, parsed.is_ipv6());
                assert_eq!(server.classification, IpClassification::classify(&parsed));
            }
        } else {
            panic!("Expected ObservationPayload::Dns");
        }
    }

    #[cfg(target_os = "macos")]
    {
        assert_eq!(obs.privilege_level, PrivilegeStatus::Unsupported);
        assert_eq!(obs.confidence, ConfidenceScore::HEURISTIC);
    }
}

#[test]
fn test_linux_resolv_conf_standard_parsing() {
    let fixture = r#"
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1
nameserver 8.8.8.8
nameserver 8.8.4.4
search corp.local example.com
options edns0 trust-ad
"#;

    let (servers, domains) = parse_resolv_conf(fixture);

    assert_eq!(servers.len(), 3);
    assert_eq!(servers[0].server_address, "192.168.1.1");
    assert!(!servers[0].is_ipv6);
    assert_eq!(servers[0].classification, IpClassification::Private);

    assert_eq!(servers[1].server_address, "8.8.8.8");
    assert!(!servers[1].is_ipv6);
    assert_eq!(servers[1].classification, IpClassification::PublicGlobal);

    assert_eq!(servers[2].server_address, "8.8.4.4");
    assert!(!servers[2].is_ipv6);
    assert_eq!(servers[2].classification, IpClassification::PublicGlobal);

    assert_eq!(domains.len(), 2);
    assert_eq!(domains[0], "corp.local");
    assert_eq!(domains[1], "example.com");
}

#[test]
fn test_linux_resolv_conf_ipv6_and_scoped_link_local() {
    let fixture = r#"
; IPv6 DNS nameservers
nameserver 2001:4860:4860::8888
nameserver fe80::1%eth0
search subnet.v6.local
"#;

    let (servers, domains) = parse_resolv_conf(fixture);

    assert_eq!(servers.len(), 2);

    assert_eq!(servers[0].server_address, "2001:4860:4860::8888");
    assert!(servers[0].is_ipv6);
    assert_eq!(servers[0].interface_name, None);
    assert_eq!(servers[0].classification, IpClassification::PublicGlobal);

    assert_eq!(servers[1].server_address, "fe80::1");
    assert!(servers[1].is_ipv6);
    assert_eq!(servers[1].interface_name, Some("eth0".to_string()));
    assert_eq!(servers[1].classification, IpClassification::LinkLocal);

    assert_eq!(domains, vec!["subnet.v6.local"]);
}

#[test]
fn test_linux_systemd_resolved_stub_handling() {
    let fixture = r#"
# This is /run/systemd/resolve/stub-resolv.conf managed by systemd-resolved(8).
nameserver 127.0.0.53
options edns0 trust-ad
search lan
"#;

    let (servers, domains) = parse_resolv_conf(fixture);

    assert_eq!(servers.len(), 1);
    assert_eq!(servers[0].server_address, "127.0.0.53");
    assert!(!servers[0].is_ipv6);
    assert_eq!(servers[0].classification, IpClassification::Loopback);
    assert_eq!(domains, vec!["lan"]);
}

#[test]
fn test_malformed_resolv_conf_resilience() {
    let fixture = r#"
# Corrupted lines and invalid entries
nameserver not_an_ip
nameserver 999.999.999.999
nameserver
nameserver 1.1.1.1 # Cloudflare DNS
nameserver 0.0.0.0
nameserver ::
search
domain test.internal
random_garbage_directive 12345
"#;

    let (servers, domains) = parse_resolv_conf(fixture);

    assert_eq!(servers.len(), 1);
    assert_eq!(servers[0].server_address, "1.1.1.1");
    assert_eq!(servers[0].classification, IpClassification::PublicGlobal);
    assert_eq!(domains, vec!["test.internal"]);
}

#[test]
fn test_empty_dns_configuration_state() {
    let fixture = "";
    let (servers, domains) = parse_resolv_conf(fixture);

    assert!(servers.is_empty());
    assert!(domains.is_empty());
}

#[test]
fn test_distinct_state_representation() {
    // 1. Available with DNS servers
    let available_with_servers = Observation::new(
        DeviceId::new(),
        "scanner.dns.v1",
        ObservationType::Dns,
        TargetDescriptor::Host {
            hostname: "test-host".to_string(),
        },
        5,
        PrivilegeStatus::Available,
        ConfidenceScore::KERNEL_AUTHORITATIVE,
        SensitivityLevel::Internal,
        ObservationPayload::Dns(DnsObservationPayload {
            dns_servers: vec![DnsServerRecord {
                server_address: "192.168.1.1".to_string(),
                interface_name: Some("Ethernet".to_string()),
                is_ipv6: false,
                classification: IpClassification::Private,
            }],
            search_domains: vec!["lan".to_string()],
            is_dynamic_dns_enabled: None,
        }),
    )
    .unwrap();

    // 2. Available but empty (e.g. host with static IP and no DNS configured)
    let available_empty = Observation::new(
        DeviceId::new(),
        "scanner.dns.v1",
        ObservationType::Dns,
        TargetDescriptor::Host {
            hostname: "isolated-host".to_string(),
        },
        2,
        PrivilegeStatus::Available,
        ConfidenceScore::KERNEL_AUTHORITATIVE,
        SensitivityLevel::Internal,
        ObservationPayload::Dns(DnsObservationPayload {
            dns_servers: Vec::new(),
            search_domains: Vec::new(),
            is_dynamic_dns_enabled: None,
        }),
    )
    .unwrap();

    // 3. Explicit Unsupported (macOS stub)
    let unsupported = Observation::new(
        DeviceId::new(),
        "scanner.dns.v1",
        ObservationType::Dns,
        TargetDescriptor::Host {
            hostname: "mac-host".to_string(),
        },
        0,
        PrivilegeStatus::Unsupported,
        ConfidenceScore::HEURISTIC,
        SensitivityLevel::Internal,
        ObservationPayload::Dns(DnsObservationPayload::default()),
    )
    .unwrap();

    // Verify distinct states
    assert_eq!(
        available_with_servers.privilege_level,
        PrivilegeStatus::Available
    );
    assert_eq!(available_empty.privilege_level, PrivilegeStatus::Available);
    assert_eq!(unsupported.privilege_level, PrivilegeStatus::Unsupported);
    assert_eq!(unsupported.confidence, ConfidenceScore::HEURISTIC);

    if let ObservationPayload::Dns(p1) = available_with_servers.payload {
        assert_eq!(p1.dns_servers.len(), 1);
    }
    if let ObservationPayload::Dns(p2) = available_empty.payload {
        assert!(p2.dns_servers.is_empty());
    }
    if let ObservationPayload::Dns(p3) = unsupported.payload {
        assert!(p3.dns_servers.is_empty());
    }
}

#[test]
fn test_dns_server_ip_classification() {
    let test_cases = [
        ("127.0.0.1", IpClassification::Loopback),
        ("127.0.0.53", IpClassification::Loopback),
        ("::1", IpClassification::Loopback),
        ("192.168.1.1", IpClassification::Private),
        ("10.0.0.1", IpClassification::Private),
        ("172.16.0.1", IpClassification::Private),
        ("fc00::1", IpClassification::Private),
        ("8.8.8.8", IpClassification::PublicGlobal),
        ("1.1.1.1", IpClassification::PublicGlobal),
        ("2001:4860:4860::8888", IpClassification::PublicGlobal),
        ("169.254.1.1", IpClassification::LinkLocal),
        ("fe80::1", IpClassification::LinkLocal),
        ("100.64.0.1", IpClassification::CarrierGradeNat),
    ];

    for (ip_str, expected_class) in test_cases {
        let ip = IpAddr::from_str(ip_str).expect("Valid IP address");
        assert_eq!(
            IpClassification::classify(&ip),
            expected_class,
            "Classification mismatch for {}",
            ip_str
        );
    }
}

#[test]
fn test_target_descriptor_dns_keys() {
    let d1 = TargetDescriptor::DnsServer {
        server_address: "1.1.1.1".to_string(),
    };
    assert_eq!(d1.target_key(), "dns_server:1.1.1.1");

    let d2 = TargetDescriptor::DnsServer {
        server_address: "2001:4860:4860::8888".to_string(),
    };
    assert_eq!(d2.target_key(), "dns_server:2001:4860:4860::8888");
}

#[test]
fn test_deterministic_dns_sorting() {
    let mut servers = [
        DnsServerRecord {
            server_address: "8.8.8.8".to_string(),
            interface_name: Some("Wi-Fi".to_string()),
            is_ipv6: false,
            classification: IpClassification::PublicGlobal,
        },
        DnsServerRecord {
            server_address: "192.168.1.1".to_string(),
            interface_name: Some("Ethernet".to_string()),
            is_ipv6: false,
            classification: IpClassification::Private,
        },
        DnsServerRecord {
            server_address: "2001:4860:4860::8888".to_string(),
            interface_name: Some("Ethernet".to_string()),
            is_ipv6: true,
            classification: IpClassification::PublicGlobal,
        },
    ];

    // Primary sort: is_ipv6, server_address, interface_name
    servers.sort_by(|a, b| {
        a.is_ipv6
            .cmp(&b.is_ipv6)
            .then_with(|| a.server_address.cmp(&b.server_address))
            .then_with(|| a.interface_name.cmp(&b.interface_name))
    });

    assert_eq!(servers[0].server_address, "192.168.1.1");
    assert_eq!(servers[1].server_address, "8.8.8.8");
    assert_eq!(servers[2].server_address, "2001:4860:4860::8888");
}

#[tokio::test]
async fn test_observation_queue_persistence_and_retrieval() {
    let db = DatabaseEngine::in_memory().expect("Failed to create in-memory database");
    let device_id = DeviceId::new();
    let scanner = PlatformDnsScanner::new();
    let obs = scanner.scan(&device_id).await.expect("Scan failed");

    let payload_json = serde_json::to_string(&obs.payload).unwrap();
    let obs_type_str = format!("{:?}", obs.observation_type).to_lowercase();

    // 1. Enqueue observation into SQLite queue
    let entry = db
        .with_writer(move |conn| {
            ObservationQueueRepository::enqueue(conn, &obs_type_str, &payload_json, None)
        })
        .await
        .expect("Enqueue failed");

    assert_eq!(entry.observation_type, "dns");
    assert_eq!(entry.status, ObservationStatus::Queued);
    assert_eq!(entry.retry_count, 0);
    assert_eq!(entry.sha256_hash.len(), 64);

    // 2. Fetch queued batch
    let batch = db
        .with_reader(|conn| ObservationQueueRepository::fetch_queued_batch(conn, 10))
        .await
        .expect("Fetch failed");

    assert_eq!(batch.len(), 1);
    assert_eq!(batch[0].id, entry.id);

    // 3. Mark in-flight
    let ids = vec![entry.id.clone()];
    let updated = db
        .with_writer(move |conn| ObservationQueueRepository::mark_in_flight(conn, &ids))
        .await
        .expect("Mark in-flight failed");
    assert_eq!(updated, 1);

    // 4. Mark acknowledged
    let ids_ack = vec![entry.id.clone()];
    let acked = db
        .with_writer(move |conn| ObservationQueueRepository::mark_acknowledged(conn, &ids_ack))
        .await
        .expect("Mark acknowledged failed");
    assert_eq!(acked, 1);
}

struct FaultyDnsScanner;

#[async_trait::async_trait]
impl PostureScanner for FaultyDnsScanner {
    fn scanner_id(&self) -> &'static str {
        "scanner.faulty_dns.v1"
    }

    fn domain(&self) -> ObservationType {
        ObservationType::Dns
    }

    async fn scan(&self, _device_id: &DeviceId) -> netra_core::error::Result<Observation> {
        Err(netra_core::error::NetraError::platform(
            "Simulated DNS failure",
        ))
    }
}

#[tokio::test]
async fn test_scanner_supervisor_failure_isolation_with_dns() {
    use netra_core::observation::ScannerSupervisor;

    let db = Arc::new(DatabaseEngine::in_memory().expect("Failed to create in-memory db"));
    let device_id = DeviceId::new();

    // Register 1 working DNS scanner and 1 faulty scanner
    let scanners: Vec<Arc<dyn PostureScanner>> = vec![
        Arc::new(PlatformDnsScanner::new()),
        Arc::new(FaultyDnsScanner),
    ];

    let supervisor = ScannerSupervisor::new(db.clone(), scanners);
    let result = supervisor
        .run_scan_cycle(&device_id)
        .await
        .expect("Supervisor cycle should succeed even if one scanner fails");

    assert_eq!(result.total_scanners, 2);
    assert_eq!(result.successful_scanners, 1);
    assert_eq!(result.observations_collected, 1);
}

#[test]
fn test_passive_architectural_invariants() {
    let dns_scanner = PlatformDnsScanner::new();
    assert_eq!(dns_scanner.scanner_id(), "scanner.dns.v1");
    assert_eq!(dns_scanner.domain(), ObservationType::Dns);
}

#[test]
fn test_windows_dns_suffix_aggregation_semantics() {
    // Tests that search_domains correctly preserves unique adapter suffixes
    let mut search_domains: Vec<String> = Vec::new();
    let adapter_suffixes = ["corp.local", "corp.local", "backup.lan", ""];

    for &suffix in &adapter_suffixes {
        let s = suffix.trim().to_string();
        if !s.is_empty() && !search_domains.contains(&s) {
            search_domains.push(s);
        }
    }

    assert_eq!(search_domains.len(), 2);
    assert_eq!(search_domains[0], "corp.local");
    assert_eq!(search_domains[1], "backup.lan");
}
