use serde::{Deserialize, Serialize};

use crate::observation::{Observation, ObservationType, TargetDescriptor};
use crate::storage::FindingSeverity;

/// A raw finding generated by a posture evaluation rule prior to deduplication and persistence.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RawFinding {
    pub title: String,
    pub description: String,
    pub severity: FindingSeverity,
    pub target: TargetDescriptor,
    pub discriminator: String,
    pub remediation_guidance: Option<String>,
    pub raw_evidence: serde_json::Value,
}

/// Abstract contract for deterministic security posture evaluation rules.
pub trait FindingRule: Send + Sync {
    /// Unique stable identifier of the rule (e.g. `NET-001-PLAINTEXT-PORT`).
    fn rule_id(&self) -> &'static str;

    /// Rule schema version.
    fn version(&self) -> u32;

    /// Observation domain evaluated by this rule.
    fn domain(&self) -> ObservationType;

    /// Default finding severity.
    fn default_severity(&self) -> FindingSeverity;

    /// Evaluates a normalized observation and returns zero or more raw findings.
    fn evaluate(&self, obs: &Observation) -> Vec<RawFinding>;
}
