# Configuration for cargo-deny to enforce security, license, and dependency hygiene
[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "CC0-1.0",
    "Zlib",
    "OpenSSL",
    "MPL-2.0",
    "0BSD"
]
confidence-threshold = 0.8
unused-allowed-license = "allow"

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
